//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4971
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBS.HamptonDwell.Web.Logic.Services.MessageQueues
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageQueueRequest", Namespace="http://schemas.datacontract.org/2004/07/EBS.HamptonDwell.Services.MessageQueues")]
    public partial class MessageQueueRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<bool> ActiveField;
        
        private string CreatedByField;
        
        private System.Nullable<int> CreatedByUserIdField;
        
        private System.Nullable<System.DateTime> CreatedOnField;
        
        private string MessageBodyField;
        
        private int MessageQueueIdField;
        
        private string MessageResponseField;
        
        private string ModifiedByField;
        
        private System.Nullable<int> ModifiedByUserIdField;
        
        private System.Nullable<System.DateTime> ModifiedOnField;
        
        private System.Nullable<System.DateTime> OccurredOnField;
        
        private int Status_MessageQueueStatusIDField;
        
        private int Type_MessageQueueTypeIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreatedByUserId
        {
            get
            {
                return this.CreatedByUserIdField;
            }
            set
            {
                this.CreatedByUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageBody
        {
            get
            {
                return this.MessageBodyField;
            }
            set
            {
                this.MessageBodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessageQueueId
        {
            get
            {
                return this.MessageQueueIdField;
            }
            set
            {
                this.MessageQueueIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageResponse
        {
            get
            {
                return this.MessageResponseField;
            }
            set
            {
                this.MessageResponseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this.ModifiedByField;
            }
            set
            {
                this.ModifiedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ModifiedByUserId
        {
            get
            {
                return this.ModifiedByUserIdField;
            }
            set
            {
                this.ModifiedByUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.ModifiedOnField;
            }
            set
            {
                this.ModifiedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OccurredOn
        {
            get
            {
                return this.OccurredOnField;
            }
            set
            {
                this.OccurredOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status_MessageQueueStatusID
        {
            get
            {
                return this.Status_MessageQueueStatusIDField;
            }
            set
            {
                this.Status_MessageQueueStatusIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type_MessageQueueTypeID
        {
            get
            {
                return this.Type_MessageQueueTypeIDField;
            }
            set
            {
                this.Type_MessageQueueTypeIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageQueueResponse", Namespace="Services.MessageQueues")]
    public partial class MessageQueueResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private EBS.HamptonDwell.Web.Logic.Services.MessageQueues.MessageQueueObject MessageQueueField;
        
        private System.Collections.Generic.List<EBS.HamptonDwell.Web.Logic.Services.MessageQueues.MessageQueueObject> MessageQueueListField;
        
        private int ResultSetCountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EBS.HamptonDwell.Web.Logic.Services.MessageQueues.MessageQueueObject MessageQueue
        {
            get
            {
                return this.MessageQueueField;
            }
            set
            {
                this.MessageQueueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<EBS.HamptonDwell.Web.Logic.Services.MessageQueues.MessageQueueObject> MessageQueueList
        {
            get
            {
                return this.MessageQueueListField;
            }
            set
            {
                this.MessageQueueListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultSetCount
        {
            get
            {
                return this.ResultSetCountField;
            }
            set
            {
                this.ResultSetCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageQueueObject", Namespace="http://schemas.datacontract.org/2004/07/EBS.HamptonDwell.Services.MessageQueues")]
    public partial class MessageQueueObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<bool> ActiveField;
        
        private string CreatedByField;
        
        private System.Nullable<int> CreatedByUserIdField;
        
        private System.Nullable<System.DateTime> CreatedOnField;
        
        private string MessageBodyField;
        
        private int MessageQueueIdField;
        
        private string MessageResponseField;
        
        private string ModifiedByField;
        
        private System.Nullable<int> ModifiedByUserIdField;
        
        private System.Nullable<System.DateTime> ModifiedOnField;
        
        private System.Nullable<System.DateTime> OccurredOnField;
        
        private int Status_MessageQueueStatusIDField;
        
        private int Type_MessageQueueTypeIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreatedByUserId
        {
            get
            {
                return this.CreatedByUserIdField;
            }
            set
            {
                this.CreatedByUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageBody
        {
            get
            {
                return this.MessageBodyField;
            }
            set
            {
                this.MessageBodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessageQueueId
        {
            get
            {
                return this.MessageQueueIdField;
            }
            set
            {
                this.MessageQueueIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageResponse
        {
            get
            {
                return this.MessageResponseField;
            }
            set
            {
                this.MessageResponseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this.ModifiedByField;
            }
            set
            {
                this.ModifiedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ModifiedByUserId
        {
            get
            {
                return this.ModifiedByUserIdField;
            }
            set
            {
                this.ModifiedByUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.ModifiedOnField;
            }
            set
            {
                this.ModifiedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OccurredOn
        {
            get
            {
                return this.OccurredOnField;
            }
            set
            {
                this.OccurredOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status_MessageQueueStatusID
        {
            get
            {
                return this.Status_MessageQueueStatusIDField;
            }
            set
            {
                this.Status_MessageQueueStatusIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type_MessageQueueTypeID
        {
            get
            {
                return this.Type_MessageQueueTypeIDField;
            }
            set
            {
                this.Type_MessageQueueTypeIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageQueueFault", Namespace="http://schemas.datacontract.org/2004/07/EBS.HamptonDwell.Services.MessageQueues")]
    public partial class MessageQueueFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:localhost/MessageQueue", ConfigurationName="EBS.HamptonDwell.Web.Logic.Services.MessageQueues.MessageQueueService")]
    public interface MessageQueueService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="GetMessageQueueRequest", ReplyAction="GetMessageQueueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EBS.HamptonDwell.Web.Logic.Services.MessageQueues.MessageQueueFault), Action="", Name="MessageQueueFault", Namespace="MessageQueueFault")]
        EBS.HamptonDwell.Web.Logic.Services.MessageQueues.MessageQueueResponse GetPendingMessageQueue(EBS.HamptonDwell.Web.Logic.Services.MessageQueues.MessageQueueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SaveMessageQueue", ReplyAction="SaveMessageQueue")]
        [System.ServiceModel.FaultContractAttribute(typeof(EBS.HamptonDwell.Web.Logic.Services.MessageQueues.MessageQueueFault), Action="", Name="MessageQueueFault", Namespace="MessageQueueFault")]
        EBS.HamptonDwell.Web.Logic.Services.MessageQueues.MessageQueueResponse Save(EBS.HamptonDwell.Web.Logic.Services.MessageQueues.MessageQueueRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface MessageQueueServiceChannel : EBS.HamptonDwell.Web.Logic.Services.MessageQueues.MessageQueueService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MessageQueueServiceClient : System.ServiceModel.ClientBase<EBS.HamptonDwell.Web.Logic.Services.MessageQueues.MessageQueueService>, EBS.HamptonDwell.Web.Logic.Services.MessageQueues.MessageQueueService
    {
        
        public MessageQueueServiceClient()
        {
        }
        
        public MessageQueueServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MessageQueueServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MessageQueueServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MessageQueueServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public EBS.HamptonDwell.Web.Logic.Services.MessageQueues.MessageQueueResponse GetPendingMessageQueue(EBS.HamptonDwell.Web.Logic.Services.MessageQueues.MessageQueueRequest request)
        {
            return base.Channel.GetPendingMessageQueue(request);
        }
        
        public EBS.HamptonDwell.Web.Logic.Services.MessageQueues.MessageQueueResponse Save(EBS.HamptonDwell.Web.Logic.Services.MessageQueues.MessageQueueRequest request)
        {
            return base.Channel.Save(request);
        }
    }
}
