//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4963
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBS.HamptonDwell.Web.Logic.Services.RewriteRules
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RewriteRuleRequest", Namespace="http://schemas.datacontract.org/2004/07/EBS.HamptonDwell.Services.RewriteRules")]
    public partial class RewriteRuleRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ActiveField;
        
        private string RewriteField;
        
        private int RewriteRuleIdField;
        
        private string UrlField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rewrite
        {
            get
            {
                return this.RewriteField;
            }
            set
            {
                this.RewriteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RewriteRuleId
        {
            get
            {
                return this.RewriteRuleIdField;
            }
            set
            {
                this.RewriteRuleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RewriteRuleResponse", Namespace="Services.RewriteRules")]
    public partial class RewriteRuleResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ResultSetCountField;
        
        private EBS.HamptonDwell.Web.Logic.Services.RewriteRules.RewriteRuleObject RewriteRuleField;
        
        private System.Collections.Generic.List<EBS.HamptonDwell.Web.Logic.Services.RewriteRules.RewriteRuleObject> RewriteRuleListField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultSetCount
        {
            get
            {
                return this.ResultSetCountField;
            }
            set
            {
                this.ResultSetCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EBS.HamptonDwell.Web.Logic.Services.RewriteRules.RewriteRuleObject RewriteRule
        {
            get
            {
                return this.RewriteRuleField;
            }
            set
            {
                this.RewriteRuleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<EBS.HamptonDwell.Web.Logic.Services.RewriteRules.RewriteRuleObject> RewriteRuleList
        {
            get
            {
                return this.RewriteRuleListField;
            }
            set
            {
                this.RewriteRuleListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RewriteRuleObject", Namespace="http://schemas.datacontract.org/2004/07/EBS.HamptonDwell.Services.RewriteRules")]
    public partial class RewriteRuleObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ActiveField;
        
        private string CreatedByField;
        
        private int CreatedByUserIdField;
        
        private System.DateTime CreatedOnField;
        
        private string ModifiedByField;
        
        private int ModifiedByUserIdField;
        
        private System.DateTime ModifiedOnField;
        
        private string RewriteField;
        
        private int RewriteRuleIdField;
        
        private string UrlField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatedByUserId
        {
            get
            {
                return this.CreatedByUserIdField;
            }
            set
            {
                this.CreatedByUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this.ModifiedByField;
            }
            set
            {
                this.ModifiedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModifiedByUserId
        {
            get
            {
                return this.ModifiedByUserIdField;
            }
            set
            {
                this.ModifiedByUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedOn
        {
            get
            {
                return this.ModifiedOnField;
            }
            set
            {
                this.ModifiedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rewrite
        {
            get
            {
                return this.RewriteField;
            }
            set
            {
                this.RewriteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RewriteRuleId
        {
            get
            {
                return this.RewriteRuleIdField;
            }
            set
            {
                this.RewriteRuleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RewriteRuleFault", Namespace="http://schemas.datacontract.org/2004/07/EBS.HamptonDwell.Services.RewriteRules")]
    public partial class RewriteRuleFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:localhost/RewriteRules", ConfigurationName="EBS.HamptonDwell.Web.Logic.Services.RewriteRules.RewriteRuleService")]
    public interface RewriteRuleService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="GetRewriteRuleRequest", ReplyAction="GetRewriteRuleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EBS.HamptonDwell.Web.Logic.Services.RewriteRules.RewriteRuleFault), Action="", Name="RewriteRuleFault", Namespace="RewriteRuleFault")]
        EBS.HamptonDwell.Web.Logic.Services.RewriteRules.RewriteRuleResponse GetRewriteRuleByUrl(EBS.HamptonDwell.Web.Logic.Services.RewriteRules.RewriteRuleRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface RewriteRuleServiceChannel : EBS.HamptonDwell.Web.Logic.Services.RewriteRules.RewriteRuleService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class RewriteRuleServiceClient : System.ServiceModel.ClientBase<EBS.HamptonDwell.Web.Logic.Services.RewriteRules.RewriteRuleService>, EBS.HamptonDwell.Web.Logic.Services.RewriteRules.RewriteRuleService
    {
        
        public RewriteRuleServiceClient()
        {
        }
        
        public RewriteRuleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public RewriteRuleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RewriteRuleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RewriteRuleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public EBS.HamptonDwell.Web.Logic.Services.RewriteRules.RewriteRuleResponse GetRewriteRuleByUrl(EBS.HamptonDwell.Web.Logic.Services.RewriteRules.RewriteRuleRequest request)
        {
            return base.Channel.GetRewriteRuleByUrl(request);
        }
    }
}
