//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4971
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBS.HamptonDwell.Web.Logic.Services.SystemConstants
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemConstantRequest", Namespace="http://schemas.datacontract.org/2004/07/EBS.HamptonDwell.Services.SystemConstants" +
        "")]
    public partial class SystemConstantRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ActiveField;
        
        private string ConstantValueField;
        
        private System.Nullable<int> CreateByUserIdField;
        
        private string FirstLetterField;
        
        private int MaximumRowsField;
        
        private int ModifiedByUserIdField;
        
        private string NameField;
        
        private EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SortBy SortByField;
        
        private EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SortDirection SortDirectionField;
        
        private int StartRowIndexField;
        
        private int SystemConstantIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConstantValue
        {
            get
            {
                return this.ConstantValueField;
            }
            set
            {
                this.ConstantValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreateByUserId
        {
            get
            {
                return this.CreateByUserIdField;
            }
            set
            {
                this.CreateByUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstLetter
        {
            get
            {
                return this.FirstLetterField;
            }
            set
            {
                this.FirstLetterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaximumRows
        {
            get
            {
                return this.MaximumRowsField;
            }
            set
            {
                this.MaximumRowsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModifiedByUserId
        {
            get
            {
                return this.ModifiedByUserIdField;
            }
            set
            {
                this.ModifiedByUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SortBy SortBy
        {
            get
            {
                return this.SortByField;
            }
            set
            {
                this.SortByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SortDirection SortDirection
        {
            get
            {
                return this.SortDirectionField;
            }
            set
            {
                this.SortDirectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartRowIndex
        {
            get
            {
                return this.StartRowIndexField;
            }
            set
            {
                this.StartRowIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SystemConstantId
        {
            get
            {
                return this.SystemConstantIdField;
            }
            set
            {
                this.SystemConstantIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SortBy", Namespace="Services.SystemConstants")]
    public enum SortBy : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Name = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ModifiedOn = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreatedOn = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SortDirection", Namespace="Services.SystemConstants")]
    public enum SortDirection : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ASC = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DESC = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NONE = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemConstantResponse", Namespace="Services.SystemConstants")]
    public partial class SystemConstantResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ResultSetCountField;
        
        private EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantObject SystemConstantField;
        
        private System.Collections.Generic.List<EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantObject> SystemConstantListField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultSetCount
        {
            get
            {
                return this.ResultSetCountField;
            }
            set
            {
                this.ResultSetCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantObject SystemConstant
        {
            get
            {
                return this.SystemConstantField;
            }
            set
            {
                this.SystemConstantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantObject> SystemConstantList
        {
            get
            {
                return this.SystemConstantListField;
            }
            set
            {
                this.SystemConstantListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemConstantObject", Namespace="http://schemas.datacontract.org/2004/07/EBS.HamptonDwell.Services.SystemConstants" +
        "")]
    public partial class SystemConstantObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ActiveField;
        
        private string ConstantValueField;
        
        private string CreatedByField;
        
        private int CreatedByUserIdField;
        
        private System.DateTime CreatedOnField;
        
        private string ModifiedByField;
        
        private int ModifiedByUserIdField;
        
        private System.DateTime ModifiedOnField;
        
        private string NameField;
        
        private int SystemConstantIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConstantValue
        {
            get
            {
                return this.ConstantValueField;
            }
            set
            {
                this.ConstantValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatedByUserId
        {
            get
            {
                return this.CreatedByUserIdField;
            }
            set
            {
                this.CreatedByUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this.ModifiedByField;
            }
            set
            {
                this.ModifiedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModifiedByUserId
        {
            get
            {
                return this.ModifiedByUserIdField;
            }
            set
            {
                this.ModifiedByUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedOn
        {
            get
            {
                return this.ModifiedOnField;
            }
            set
            {
                this.ModifiedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SystemConstantId
        {
            get
            {
                return this.SystemConstantIdField;
            }
            set
            {
                this.SystemConstantIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemConstantFault", Namespace="http://schemas.datacontract.org/2004/07/EBS.HamptonDwell.Services.SystemConstants" +
        "")]
    public partial class SystemConstantFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:localhost/SystemConstants", ConfigurationName="EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantService")]
    public interface SystemConstantService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="GetSystemConstantRequest", ReplyAction="GetSystemConstantResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantFault), Action="", Name="SystemConstantFault", Namespace="SystemConstantFault")]
        EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantResponse GetSystemConstantById(EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetSystemConstantByName", ReplyAction="GetSystemConstantResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantFault), Action="", Name="SystemConstantFault", Namespace="SystemConstantFault")]
        EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantResponse GetSystemConstantByName(EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetSystemConstantList", ReplyAction="GetSystemConstantResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantFault), Action="", Name="SystemConstantFault", Namespace="SystemConstantFault")]
        EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantResponse GetSystemConstantList(EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SaveSystemConstant", ReplyAction="SaveSystemConstant")]
        [System.ServiceModel.FaultContractAttribute(typeof(EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantFault), Action="", Name="SystemConstantFault", Namespace="SystemConstantFault")]
        EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantResponse Save(EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SaveSystemConstantByName", ReplyAction="SaveSystemConstantByName")]
        [System.ServiceModel.FaultContractAttribute(typeof(EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantFault), Action="", Name="SystemConstantFault", Namespace="SystemConstantFault")]
        EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantResponse SaveSystemConstantByName(EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SystemConstantServiceChannel : EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SystemConstantServiceClient : System.ServiceModel.ClientBase<EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantService>, EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantService
    {
        
        public SystemConstantServiceClient()
        {
        }
        
        public SystemConstantServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public SystemConstantServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SystemConstantServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SystemConstantServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantResponse GetSystemConstantById(EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantRequest request)
        {
            return base.Channel.GetSystemConstantById(request);
        }
        
        public EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantResponse GetSystemConstantByName(EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantRequest request)
        {
            return base.Channel.GetSystemConstantByName(request);
        }
        
        public EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantResponse GetSystemConstantList(EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantRequest request)
        {
            return base.Channel.GetSystemConstantList(request);
        }
        
        public EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantResponse Save(EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantRequest request)
        {
            return base.Channel.Save(request);
        }
        
        public EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantResponse SaveSystemConstantByName(EBS.HamptonDwell.Web.Logic.Services.SystemConstants.SystemConstantRequest request)
        {
            return base.Channel.SaveSystemConstantByName(request);
        }
    }
}
