//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4971
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBS.HamptonDwell.Web.Logic.Services.VirtualPages
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VirtualPageRequest", Namespace="http://schemas.datacontract.org/2004/07/EBS.HamptonDwell.Services.VirtualPages")]
    public partial class VirtualPageRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ActiveField;
        
        private System.Nullable<int> CreatedByUserIdField;
        
        private string FirstLetterField;
        
        private bool IsTemplateField;
        
        private string KeywordsField;
        
        private int MaximumRowsField;
        
        private System.Nullable<int> MemberOfField;
        
        private string MetaDescriptionField;
        
        private System.Nullable<int> ModifiedByUserIdField;
        
        private string PageContentField;
        
        private string PageNameField;
        
        private System.Nullable<int> PageTemplateField;
        
        private string PageTitleField;
        
        private string PathField;
        
        private EBS.HamptonDwell.Web.Logic.Services.VirtualPages.SortBy SortByField;
        
        private EBS.HamptonDwell.Web.Logic.Services.VirtualPages.SortDirection SortDirectionField;
        
        private int StartRowIndexField;
        
        private int VirtualPageIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreatedByUserId
        {
            get
            {
                return this.CreatedByUserIdField;
            }
            set
            {
                this.CreatedByUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstLetter
        {
            get
            {
                return this.FirstLetterField;
            }
            set
            {
                this.FirstLetterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTemplate
        {
            get
            {
                return this.IsTemplateField;
            }
            set
            {
                this.IsTemplateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Keywords
        {
            get
            {
                return this.KeywordsField;
            }
            set
            {
                this.KeywordsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaximumRows
        {
            get
            {
                return this.MaximumRowsField;
            }
            set
            {
                this.MaximumRowsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MemberOf
        {
            get
            {
                return this.MemberOfField;
            }
            set
            {
                this.MemberOfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetaDescription
        {
            get
            {
                return this.MetaDescriptionField;
            }
            set
            {
                this.MetaDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ModifiedByUserId
        {
            get
            {
                return this.ModifiedByUserIdField;
            }
            set
            {
                this.ModifiedByUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PageContent
        {
            get
            {
                return this.PageContentField;
            }
            set
            {
                this.PageContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PageName
        {
            get
            {
                return this.PageNameField;
            }
            set
            {
                this.PageNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PageTemplate
        {
            get
            {
                return this.PageTemplateField;
            }
            set
            {
                this.PageTemplateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PageTitle
        {
            get
            {
                return this.PageTitleField;
            }
            set
            {
                this.PageTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EBS.HamptonDwell.Web.Logic.Services.VirtualPages.SortBy SortBy
        {
            get
            {
                return this.SortByField;
            }
            set
            {
                this.SortByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EBS.HamptonDwell.Web.Logic.Services.VirtualPages.SortDirection SortDirection
        {
            get
            {
                return this.SortDirectionField;
            }
            set
            {
                this.SortDirectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartRowIndex
        {
            get
            {
                return this.StartRowIndexField;
            }
            set
            {
                this.StartRowIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VirtualPageId
        {
            get
            {
                return this.VirtualPageIdField;
            }
            set
            {
                this.VirtualPageIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SortBy", Namespace="Services.VirtualPages")]
    public enum SortBy : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PageName = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SortDirection", Namespace="Services.VirtualPages")]
    public enum SortDirection : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ASC = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DESC = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NONE = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VirtualPageResponse", Namespace="Services.VirtualPages")]
    public partial class VirtualPageResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ResultSetCountField;
        
        private EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageObject VirtualPageField;
        
        private System.Collections.Generic.List<EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageObject> VirtualPageListField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultSetCount
        {
            get
            {
                return this.ResultSetCountField;
            }
            set
            {
                this.ResultSetCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageObject VirtualPage
        {
            get
            {
                return this.VirtualPageField;
            }
            set
            {
                this.VirtualPageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageObject> VirtualPageList
        {
            get
            {
                return this.VirtualPageListField;
            }
            set
            {
                this.VirtualPageListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VirtualPageObject", Namespace="http://schemas.datacontract.org/2004/07/EBS.HamptonDwell.Services.VirtualPages")]
    public partial class VirtualPageObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ActiveField;
        
        private int CreatedByUserIdField;
        
        private System.DateTime CreatedOnField;
        
        private bool IsTemplateField;
        
        private string KeywordsField;
        
        private int MemberOfField;
        
        private string MetaDescriptionField;
        
        private int ModifiedByUserIdField;
        
        private System.DateTime ModifiedOnField;
        
        private string PageContentField;
        
        private string PageNameField;
        
        private int PageTemplateField;
        
        private string PageTitleField;
        
        private string PathField;
        
        private int VirtualPageIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatedByUserId
        {
            get
            {
                return this.CreatedByUserIdField;
            }
            set
            {
                this.CreatedByUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTemplate
        {
            get
            {
                return this.IsTemplateField;
            }
            set
            {
                this.IsTemplateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Keywords
        {
            get
            {
                return this.KeywordsField;
            }
            set
            {
                this.KeywordsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MemberOf
        {
            get
            {
                return this.MemberOfField;
            }
            set
            {
                this.MemberOfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetaDescription
        {
            get
            {
                return this.MetaDescriptionField;
            }
            set
            {
                this.MetaDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModifiedByUserId
        {
            get
            {
                return this.ModifiedByUserIdField;
            }
            set
            {
                this.ModifiedByUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedOn
        {
            get
            {
                return this.ModifiedOnField;
            }
            set
            {
                this.ModifiedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PageContent
        {
            get
            {
                return this.PageContentField;
            }
            set
            {
                this.PageContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PageName
        {
            get
            {
                return this.PageNameField;
            }
            set
            {
                this.PageNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageTemplate
        {
            get
            {
                return this.PageTemplateField;
            }
            set
            {
                this.PageTemplateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PageTitle
        {
            get
            {
                return this.PageTitleField;
            }
            set
            {
                this.PageTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VirtualPageId
        {
            get
            {
                return this.VirtualPageIdField;
            }
            set
            {
                this.VirtualPageIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VirtualPageFault", Namespace="http://schemas.datacontract.org/2004/07/EBS.HamptonDwell.Services.VirtualPages")]
    public partial class VirtualPageFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:localhost/VirtualPages", ConfigurationName="EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageService")]
    public interface VirtualPageService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="GetVirtualPageRequest", ReplyAction="GetVirtualPageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageFault), Action="", Name="VirtualPageFault", Namespace="VirtualPageFault")]
        EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageResponse GetVirtualPageById(EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetVirtualPageByPath", ReplyAction="GetVirtualPageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageFault), Action="", Name="VirtualPageFault", Namespace="VirtualPageFault")]
        EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageResponse GetVirtualPageByPath(EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetVirtualPageList", ReplyAction="GetVirtualPageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageFault), Action="", Name="VirtualPageFault", Namespace="VirtualPageFault")]
        EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageResponse GetVirtualPageList(EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetVirtualPageTemplates", ReplyAction="GetVirtualPageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageFault), Action="", Name="VirtualPageFault", Namespace="VirtualPageFault")]
        EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageResponse GetVirtualPageTemplates(EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetVirtualPageParents", ReplyAction="GetVirtualPageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageFault), Action="", Name="VirtualPageFault", Namespace="VirtualPageFault")]
        EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageResponse GetVirtualPageParents(EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SaveVirtualPage", ReplyAction="SaveVirtualPage")]
        [System.ServiceModel.FaultContractAttribute(typeof(EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageFault), Action="", Name="VirtualPageFault", Namespace="VirtualPageFault")]
        EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageResponse Save(EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SaveKeywords", ReplyAction="SaveKeywords")]
        [System.ServiceModel.FaultContractAttribute(typeof(EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageFault), Action="", Name="VirtualPageFault", Namespace="VirtualPageFault")]
        EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageResponse SaveKeywords(EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface VirtualPageServiceChannel : EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class VirtualPageServiceClient : System.ServiceModel.ClientBase<EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageService>, EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageService
    {
        
        public VirtualPageServiceClient()
        {
        }
        
        public VirtualPageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public VirtualPageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public VirtualPageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public VirtualPageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageResponse GetVirtualPageById(EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageRequest request)
        {
            return base.Channel.GetVirtualPageById(request);
        }
        
        public EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageResponse GetVirtualPageByPath(EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageRequest request)
        {
            return base.Channel.GetVirtualPageByPath(request);
        }
        
        public EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageResponse GetVirtualPageList(EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageRequest request)
        {
            return base.Channel.GetVirtualPageList(request);
        }
        
        public EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageResponse GetVirtualPageTemplates(EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageRequest request)
        {
            return base.Channel.GetVirtualPageTemplates(request);
        }
        
        public EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageResponse GetVirtualPageParents(EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageRequest request)
        {
            return base.Channel.GetVirtualPageParents(request);
        }
        
        public EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageResponse Save(EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageRequest request)
        {
            return base.Channel.Save(request);
        }
        
        public EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageResponse SaveKeywords(EBS.HamptonDwell.Web.Logic.Services.VirtualPages.VirtualPageRequest request)
        {
            return base.Channel.SaveKeywords(request);
        }
    }
}
